name: C++ CI/CD with vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: Install dependencies with vcpkg
      run: |
        ./vcpkg/vcpkg install <package1> <package2> ...  # List your packages here
        ./vcpkg/vcpkg integrate install

    - name: Check code style with clang-format
      run: |
        sudo apt-get install -y clang-format
        echo "Checking code style with clang-format..."
        SOURCE_FILES=$(find src include -name '*.cpp' -o -name '*.hpp' -o -name '*.h' -o -name '*.cppm' -o -name '*.ixx')
        clang-format -i --verbose $SOURCE_FILES
        git diff --exit-code

    - name: Run clang-tidy
      run: |
        sudo apt-get install -y clang-tidy
        echo "Running clang-tidy..."
        SOURCE_FILES=$(find src include -name '*.cpp' -o -name '*.hpp' -o -name '*.h' -o -name '*.cppm' -o -name '*.ixx')
        clang-tidy $SOURCE_FILES -- -std=c++23
        echo "clang-tidy checks are complete."

    - name: Configure and build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build . --config Release

    - name: Run tests
      run: |
        ctest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: Install dependencies with vcpkg
      run: |
        ./vcpkg/vcpkg install <package1> <package2> ...  # List your packages here
        ./vcpkg/vcpkg integrate install

    - name: Configure and build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: build/${PROJECT_NAME}
