name: C++ CI/CD with vcpkg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: Install dependencies with vcpkg
      run: |
        ./vcpkg/vcpkg install <package1> <package2> ...  # List your packages here
        ./vcpkg/vcpkg integrate install

    - name: Configure and build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build . --config Release

    - name: Run tests
      run: |
        ctest

    - name: Check codestyle
      run: |
        echo "Check codestyle..."
        git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code
        echo "Codestyle is fine."

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: Install dependencies with vcpkg
      run: |
        ./vcpkg/vcpkg install <package1> <package2> ...  # List your packages here
        ./vcpkg/vcpkg integrate install

    - name: Configure and build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: build/${PROJECT_NAME}
